version: "3.9"

services:
  voicevox:
    image: hiroshiba/voicevox_engine:latest
    expose:
      - "50021"
    ports:
      - "50021:50021"
    restart: always
  next_app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - VOICEVOX_API_URL=http://voicevox:50021
      - VOICEVOX_SPEAKER_ID=14
    depends_on:
      - voicevox
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - next_app
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ymmtr6.works+certbot@gmail.com -d voicenews.jp --agree-tos --no-eff-email --staging
